import { readdir } from 'fs/promises';
import { join, relative } from 'path';

/**
 * Get all prose pages after a build, by reading all HTML files from the
 * given output directory, and not from assets.
 *
 * We cannot use the `assets` map here because it is not guaranteed to
 * contain all files, especially if they were generated by other integrations.
 * Other astro integrations may hijack the "[...slug]" entrypoint, and any files
 * previously in the [...slug] asset map entry would be lost (this is where starlight stores
 * its prose HTML files).
 */
export async function getProsePages({
  apiReferenceBasePath,
  outputBasePath,
}: {
  apiReferenceBasePath: string | null;
  outputBasePath: string;
}): Promise<string[]> {
  const allFiles = await readdir(outputBasePath, {
    recursive: true,
    withFileTypes: true,
  });

  const htmlFiles = allFiles
    .filter((file) => file.isFile() && file.name.endsWith('.html'))
    .map((file) => join(file.parentPath, file.name));

  if (!apiReferenceBasePath) return htmlFiles;
  // Normalize by removing leading/trailing slashes from apiReferenceBasePath
  const normalizedApiPath = apiReferenceBasePath.replace(/^\/+/g, '').replace(/\/+$/g, '');
  const pagesToRender = htmlFiles.filter((absPath) => {
    const relPath = relative(outputBasePath, absPath);
    // Filter out API reference pages
    if (relPath === normalizedApiPath || relPath.startsWith(`${normalizedApiPath}/`)) return false;
    return true;
  });

  return pagesToRender;
}
